#zuul网关配置
zuul:
  routes:
    #视图
    view:
      path: /view/**             #路由路径
      service-id: view          #指向的服务id
    #用户服务
    user-service:
      path: /user-service/**             #路由路径
      service-id: user-service          #指向的服务id


#链路追踪
spring:
  zipkin:
    base-url: http://127.0.0.1:9411  #中心地址
    sender:
      type: web   #发送方式