server:
  port: 8770


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  data:
    mongodb:
      database: online_education
      host: localhost
      port: 27017

