spring:
  application:
    name: view

server:
  port: 9080
  #port: 9081
  #port: 9082
  #port: 9083
  #port: 9084
  tomcat:
    max-connections: 10000
    max-threads: 200

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


